apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "spring-boot-rest", "namespace": "", "kind": "DeploymentConfig"}]'
    name: spring-boot-rest-pipeline
  spec:
    source:
      git:
        ref: master
        uri: https://github.com/devops-mvcs/spring-boot-rest-example.git
      type: Git
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
    triggers:
    - generic:
        secret: FiArdDBH
      type: Generic
